units:
  # kx and ky allow for easy- easi-er switching between MX and Choc.
  kx: u
  ky: u
  px: kx + 2
  py: ky + 2
  # These variables allow for updating the previews on https://ergogen.ceoloide.com
  $default_width: u
  $default_height: u
  # KiCAD places the PCB in the middle of nowhere to start with.
  # These variables give a starting place for later shifts.
  starting_x: 170
  starting_y: -150

  # Defaults to M2 Screws
  screwSize: 1
  standoffSize: 2.5

meta:
  engine: 4.1.0
points:
  key.tags: 
    - key
  zones:
    matrix:
      anchor:
        shift: [starting_x, starting_y] # Fix KiCad placement
      key:
        padding: u
        spread: u
      columns:
 
        inner:
        index:
          key:
            stagger: 4
        middle:
          key:
            stagger: 9
        ring:
          key:
            stagger: -10.3
            splay: -4
            spread: 19
        pinky:
          key:
            stagger: -14+1.23699
            splay: -6
            spread: u-0.17585
        pinky_extra:
          key:
            stagger: 5

          rows.top.skip: true


      rows:
        bottom:
          shift: [0, 0]
        home:

        top:
        

    thumb1:
      anchor:
        - ref: matrix_index_bottom
          shift: [2.95, -21.95]
      columns:
        1:
          key.anchor: matrix_index_bottom
      rows:
        r0:
    thumb2:
      anchor:
        - ref: matrix_index_bottom
          shift: [-18.16425, -24.83108]
      columns:
        2:
          key.rotate: 15
      rows:
        r0:
    thumb3:
      anchor:
        - ref: matrix_index_bottom
          shift: [-37.81425, -33.08388]
      columns:
        3:
          key.rotate: 30
      rows:
        r0:
    thumb4:
      anchor:
        - ref: matrix_index_bottom
          shift: [-54.68925, -46.14597]
      columns:
        4:
          key.rotate: 45
      rows:
        r0:

outlines:
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  pinky1:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_bottom
          shift: [10.3, -10.3]
        - ref: matrix_pinky_bottom
          shift: [-10.3, -10.3]
        - ref: matrix_pinky_top
          shift: [-10.3, 10.3]
        - ref: matrix_pinky_top
          shift: [10.3, 10.3]
      fillet: 0.7
  pinky2:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_extra_home
          shift: [10.3, 10.3]
        - ref: matrix_pinky_extra_home
          shift: [-10.3, 10.3]
        - ref: matrix_pinky_extra_bottom
          shift: [-10.3, -10.3]
        - ref: matrix_pinky_extra_bottom
          shift: [10.3, -10.3]
      fillet: 0.7
  ring:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_ring_bottom
          shift: [-10.3, -17.91695]
        - ref: matrix_ring_bottom
          shift: [10.3, -17.91695]
        - ref: matrix_ring_home
          shift: [10.3, 10.3]
        - ref: matrix_ring_home
          shift: [-10.3, 10.3]
  middle:
    - what: rectangle
      where: matrix_middle_top
      size: [20.6, 20.6]
      fillet: 0.7
  main:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_middle_top
          shift: [-78.3, -90]
        - ref: matrix_middle_top
          shift: [-78.3,6.3 ] 
        - ref: matrix_middle_top
          shift: [51.1 ,6.3]
        - ref: matrix_middle_top
          shift: [51.1 ,-40]
        - ref: matrix_middle_bottom
          shift: [20, -27.67714]
        - ref: matrix_middle_bottom
          shift: [-20, -27.67714]
      fillet: 0.7
  thumb_arc:
    - what: path
      
      segments:
        - type: line
          points:
          - ref: thumb4_4_r0
            shift: [0, 10.3]
          - ref: thumb4_4_r0
            shift: [-10.3, 10.3]
          - ref: thumb4_4_r0
            shift: [-10.3, -10.3]
          - ref: thumb4_4_r0
            shift: [0, -10.3]
        - type: arc
          points:
            - ref: thumb2_2_r0
              shift: [-9.26866, -10.87903]
            - ref: thumb1_1_r0
              shift: [0, -10.3]
        - type: line
          points:
            - ref: thumb1_1_r0
              shift: [0, -10.3]
            - ref: thumb1_1_r0
              shift: [10.3, -10.3]
            - ref: thumb1_1_r0
              shift: [10.3, 10.3]
            - ref: thumb1_1_r0
              shift: [0, 10.3]
        - type: arc
          points:
            - ref: thumb2_2_r0
              shift: [11.95286, 8.76225]
            - ref: thumb4_4_r0
              shift: [0, 10.3]
      fillet: 0.7
  board0:
    - name: pinky1
      operation: add
    - name: ring
    - name: thumb_arc
    - name: middle
    - name: main
    - name: pinky2
  break:
    - what: polygon
      operation: stack
      points:
      - ref: matrix_pinky_top
        shift: [10.3, 10.3]
      - ref: matrix_pinky_top
        shift: [10.3, -8]
      - ref: matrix_pinky_top
        shift: [11.3, -8]
      - ref: matrix_pinky_top
        shift: [11.3, 10.3]
      fillet: 0.49
  breakaway2:
    - what: polygon
      operation: add
      points:
        - ref: matrix_pinky_top
          shift: [10.3, -19.5]
        - ref: matrix_pinky_bottom
          shift: [10.3, 10.5]
        - ref: matrix_pinky_bottom
          shift: [11.3, 10.5]
        - ref: matrix_pinky_top
          shift: [11.3, -19.5]
      fillet: 0.45
#  breakaway_pinky3:
#    - what: polygon
#      operation: add
#      points:
#        - ref: matrix_pinky_top
#          shift: [10.3, -25]
#        - ref: matrix_pinky_bottom
#          shift: [10.3, 10.5]
#        - ref: matrix_pinky_bottom
#          shift: [11.3, 10.5]
#        - ref: matrix_pinky_top
#          shift: [11.3, -25]
#      fillet: 0.49
  breakaway_pinky4:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [10.3, -38.5]
        - ref: matrix_pinky_top
          shift: [10.3, -60]
        - ref: matrix_pinky_top
          shift: [11.3, -60]
        - ref: matrix_pinky_top
          shift: [11.3, -38.5]
      fillet: 0.49
#  MCU_cutout:
#    - what: rectangle
#      where: matrix_inner_top
#      size: [10.3, 9]
#      adjust:
#        shift: [-24, 15]
  haptic:
    - what: rectangle
      where: matrix_middle_top
      size: [14.4, 11.4]
      adjust:
        shift: [40, -7.75]


  break1:
    - name: break
      operation: stack
    - name: breakaway2
#    - name: breakaway_pinky3
    - name: breakaway_pinky4
#    - name: MCU_cutout
    - name: haptic

  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_extra_home
          shift: [0.5px,0.5py]
        - ref: matrix_pinky_top
          shift: [0.5px,0.5py]
        - ref: matrix_ring_top
          shift: [0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: matrix_index_top
          shift: [-0.5px,0.5py]
        - ref: matrix_inner_top
          shift: [-0.5px,0.5py]
        - ref: matrix_inner_top
          shift: [-2.65px,0.5py]
#        - ref: thumbfan_thumb4_r0
#          shift: [-0.5px,0.5py]
#        - ref: thumbfan_thumb4_r0
#          shift: [-0.5px,-0.5py]
#        - ref: thumbfan_thumb3_r0
#          shift: [0.5px,-0.5py]
        - ref: matrix_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: matrix_pinky_extra_bottom
          shift: [0.5px,-0.5py]


  thumb1:
    - what: polygon
      operation: stack
      points:
        - ref: thumb3_3_r0
          shift: [-10.6, -7.4]
        - ref: thumb3_3_r0
          shift: [-10.6, -20]
        - ref: thumb3_3_r0
          shift: [-11.6, -20]
        - ref: thumb3_3_r0
          shift: [-11.6, -7.4]
      fillet: 0.49

  thumb2:
    - what: polygon
      operation: stack
      points:
        - ref: thumb3_3_r0
          shift: [-10.6, -4.4]
        - ref: thumb3_3_r0
          shift: [-10.6, 3.2]
        - ref: thumb3_3_r0
          shift: [-11.6, 3.2]
        - ref: thumb3_3_r0
          shift: [-11.6, -4.4]
      fillet: 0.49
  thumb3:
    - what: polygon
      operation: stack
      points:
        - ref: thumb3_3_r0
          shift: [-10.6, 6.2]
        - ref: matrix_inner_bottom
          shift: [-32.2, -28]
        - ref: matrix_inner_bottom
          shift: [-45, -28]
        - ref: matrix_inner_bottom
          shift: [-45, -29]
        - ref: matrix_inner_bottom
          shift: [-32.7, -29]
        - ref: thumb3_3_r0
          shift: [-11.6, 6.2]
      fillet: 0.4

  board2:
    - name: board0
    - operation: subtract
      name: break1
    - operation: subtract
      name: thumb3
    - operation: subtract
      name: thumb2
    - operation: subtract
      name: thumb1
  #combo:
  #  - name: board2
  #  - operation: stack
  #    name: keys

  
  # combo2:
  #  - name: board2
  #  - operation: stack
  #    name: keys


pcbs:
  KLON:
    outlines:
      main:
        outline: board2
    template: kicad8
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
          include_stabilizer_pad: false
          reversible: true
    
      mx_hotswap:
          what: ceoloide/switch_mx
          where: true
          params:
            hotswap: true
            from: "{{column_net}}"
            to: "{{colrow}}"
            reversible: true
          adjust:
            rotate: 180

      diode:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -8.5]

      nicenano:
        what: ceoloide/mcu_nice_nano
        where:
          ref: matrix_inner_top
          shift: [-24, 1]
        params:
          reversible: true

      battery_connector:
        what: ceoloide/battery_connector_jst_ph_2
        where: matrix_inner_top
        adjust:
          shift: [-1kx,-1ky]
          rotate: 90

      on_off_switch:
        what: ceoloide/power_switch_smd_side
        where: matrix_inner_top
        adjust:
          shift: [-2kx, -1ky]
        params:
          from: BAT_P
          to: RAW

      reset_switch:
        what: ceoloide/reset_switch_smd_side
        params:
          from: GND
          to: RST
        where: 
          ref: matrix_inner_top

        adjust:
          shift: [-2kx, -1.5ky]
          rotate: 90
      haptic:
        what: haptic
        where: matrix_middle_top
        adjust:
          shift: [40, -7]
          rotate: 180
        params:
          P1: undefined
          P2: undefined
          P3: undefined
          P4: undefined
          P5: undefined


